export default [
	'AgentOptions.svg',
	'Asynchronous.svg',
	'Block.svg',
	'CollapsedBlocks.svg',
	'Connect.svg',
	'Divider.svg',
	'DividerMasking.svg',
	'Fade.svg',
	'Markdown.svg',
	'Parallel.svg',
	'Reference.svg',
	'ReferenceLayering.svg',
	'SelfConnect.svg',
];
