define([
	'core/ArrayUtilities_spec',
	'svg/SVGUtilities_spec',
	'svg/SVGTextBlock_spec',
	'svg/SVGShapes_spec',
	'interface/Interface_spec',
	'sequence/Parser_spec',
	'sequence/Generator_spec',
	'sequence/Renderer_spec',
	'sequence/themes/Basic_spec',
	'sequence/sequence_integration_spec',
]);
